### ISSUE TITLE
当返回值为中文时乱码

### ISSUE THREAD

**Issue by rxrddd** [crossoverJie/ptg#6]
当返回值为中文时乱码

**Comment by crossoverJie** [comment]
![image](https://user-images.githubusercontent.com/15684156/176104704-74e5f794-c88c-4da0-9482-b425bb73d76c.png)
已经修复，主要支持`阿里汉仪智能黑体，simkai.ttf，msyhl.ttc` 这三种字体，如果本地没有请自行安装一下这三种字体。
